#
# Changes to this file will be overwritten by `trmnlp pull`.
#
# Docs: https://help.usetrmnl.com/en/articles/10542599-importing-and-exporting-private-plugins#h_581fb988f0
#
---
name: Ralph Ruthe Comic
strategy: static
no_screen_padding: 'no'
dark_mode: 'no'
custom_fields:
